export const IS_DEV = import.meta.env.VITE_IS_DEV === 'true'

export const demoOrg = {
  id: 'demo-org-1',
  slug: 'aozora-art',
  name: '青空アート部',
  description:
    '大学の有志で集まったアート集団です。絵画・写真・立体など様々なジャンルの作品を年に数回展示しています。',
  sns_links: { instagram: 'https://instagram.com', x: 'https://x.com' },
  homepage_url: 'https://example.com',
}

export const demoOrgs = [
  demoOrg,
  {
    id: 'demo-org-2',
    slug: 'mono-lab',
    name: 'mono lab.',
    description: '写真と映像を軸に活動するクリエイター集団。',
    sns_links: { instagram: 'https://instagram.com' },
    homepage_url: '',
  },
]

export const demoExhibitions = [
  {
    id: 'demo-exh-1',
    organization_id: 'demo-org-1',
    slug: 'spring-2025',
    title: '春の芽吹き展',
    description: '春をテーマに集めた、色とりどりの作品たち。',
    start_date: '2025-04-01',
    start_time: '10:00',
    end_date: '2025-04-20',
    end_time: '18:00',
    location: '東京都渋谷区 ギャラリー白',
  },
  {
    id: 'demo-exh-2',
    organization_id: 'demo-org-1',
    slug: 'winter-2024',
    title: '静寂と余白',
    description: '冬の静けさをモノクロームで表現した作品展。',
    start_date: '2024-12-10',
    start_time: '11:00',
    end_date: '2024-12-22',
    end_time: '19:00',
    location: '東京都新宿区 ギャラリー銀',
  },
  {
    id: 'demo-exh-3',
    organization_id: 'demo-org-1',
    slug: 'summer-2024',
    title: '熱量と影',
    description: '夏の強い光と影のコントラストをテーマにした作品展。',
    start_date: '2024-07-15',
    start_time: '12:00',
    end_date: '2024-07-28',
    end_time: '20:00',
    location: '東京都港区 スペースAO',
  },
  {
    id: 'demo-exh-4',
    organization_id: 'demo-org-1',
    slug: 'autumn-2023',
    title: '重なりと透明',
    description: '素材の重なりと透明感を追求した、インスタレーション中心の展覧会。',
    start_date: '2023-11-03',
    start_time: '10:00',
    end_date: '2023-11-12',
    end_time: '17:00',
    location: '東京都台東区 3331 Arts Chiyoda',
  },
  {
    id: 'demo-exh-5',
    organization_id: 'demo-org-2',
    slug: 'distance-2025',
    title: '距離と眼差し',
    description: '日常の中にある「遠さ」を写真で切り取った作品展。',
    start_date: '2025-03-08',
    start_time: '11:00',
    end_date: '2025-03-16',
    end_time: '18:00',
    location: '東京都中央区 VOID+',
  },
  {
    id: 'demo-exh-6',
    organization_id: 'demo-org-2',
    slug: 'loop-2024',
    title: 'LOOP',
    description: '映像と音が循環するインスタレーション。',
    start_date: '2024-09-20',
    start_time: '13:00',
    end_date: '2024-09-29',
    end_time: '21:00',
    location: '東京都渋谷区 WWW',
  },
]

export const demoArtworks = [
  {
    id: 'demo-aw-1',
    exhibition_id: 'demo-exh-1',
    title: '光の粒子',
    description: '朝の窓から差し込む光をアクリルで描いた作品。',
    image_url: '',
    order: 1,
  },
  {
    id: 'demo-aw-2',
    exhibition_id: 'demo-exh-1',
    title: '萌え出づる',
    description: '春の新芽をモチーフにした版画シリーズ第一作。',
    image_url: '',
    order: 2,
  },
  {
    id: 'demo-aw-3',
    exhibition_id: 'demo-exh-1',
    title: '雨上がりの路',
    description: '雨上がりの石畳を水彩で表現。',
    image_url: '',
    order: 3,
  },
  {
    id: 'demo-aw-4',
    exhibition_id: 'demo-exh-2',
    title: '白と沈黙',
    description: '白い空間に置かれた小さな石。余白が語る静けさ。',
    image_url: '',
    order: 1,
  },
  {
    id: 'demo-aw-5',
    exhibition_id: 'demo-exh-2',
    title: '夜の輪郭',
    description: '鉛筆のみで描いた夜景シリーズ。',
    image_url: '',
    order: 2,
  },
]
